name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag lomot/bedrock-web-console:latest

    - name: upload image
      run: |
        docker login --username=${{ secrets.DOCKER_ID }} --password=${{ secrets.DOCKER_TOKEN }}
        docker tag lomot/bedrock-web-console:latest lomot/bedrock-web-console:base
        docker push lomot/minecraft-bedrock:base
